# Generated by Django 4.1.3 on 2022-12-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=15)),
                ("content", models.CharField(max_length=100)),
                ("postnumer", models.CharField(max_length=3)),
            ],
        ),
    ]
