# Generated by Django 4.1.3 on 2022-12-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_coment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coment",
            name="postnumer",
            field=models.IntegerField(),
        ),
    ]
